# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-16 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20151030_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['codigo_referencia'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='fundo',
            options={'ordering': ['nome'], 'verbose_name': 'Fundo', 'verbose_name_plural': 'Fundos'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['nome'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterModelOptions(
            name='publicacoes',
            options={'ordering': ['titulo'], 'verbose_name': 'Plubica\xe7\xe3o', 'verbose_name_plural': 'Publica\xe7\xf5es'},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'ordering': ['nome'], 'verbose_name': 'S\xe9rie', 'verbose_name_plural': 'S\xe9ries'},
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
